plugins:
  topic_custom_field_enabled: true
    default: true
    client: true
  topic_custom_field_name: 'ktopicinfo'
    default: 'ktopicinfo'
    client: true
  topic_custom_field_type: 'json'
    default: 'string'
    client: true
    type: enum
    choices:
      - string
      - integer
      - boolean
      - json